In [10]:
import numpy as np
arr = np.array([[1,2,3],[5,6,7]])
print(arr.shape)

(2, 3)


In [11]:
print(arr.ndim)
print(arr.size)
print(type(arr))
print(arr.dtype)

2
6
<class 'numpy.ndarray'>
int32


In [30]:
a = np.array([[1,2,3,4],[5,6,6,8],[9,1,3,4]])
print(a)
print(a[:,2:3])

[[1 2 3 4]
 [5 6 6 8]
 [9 1 3 4]]
[[3]
 [6]
 [3]]


In [ ]:
import pandas as pd
