In [1]:
import numpy as np


In [3]:
a =np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [12]:
c = np.concatenate((a,b)) 

In [15]:
c.size
c.shape


(8,)

In [17]:
c.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
arr = np.array([[1,2,3,4,5]])
arr[0,0:2]

array([1, 2])

In [25]:
x=np.arange(20)

In [28]:
x.shape = (4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
x.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [34]:
row=np.sum(x, axis=1)
row

array([10, 35, 60, 85])

In [37]:
row = np.multiply(x,5)
row

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [41]:
row+np.array([5,6,5,8,9])

array([[  5,  11,  15,  23,  29],
       [ 30,  36,  40,  48,  54],
       [ 55,  61,  65,  73,  79],
       [ 80,  86,  90,  98, 104]])